name: 'Open a Github Issue'
description: 'Opens a github Issue'
author: 'Romany Sefen'

# Define your inputs here.
inputs:
  milliseconds:
    description: 'Milliseconds to delay the process'
    required: true
    default: '1000'
  token:
    required: true
    description: 'GIT_HUB Token'
  title:
    required: true
    description: 'Title of the Issue'
  body:
    required: true
    description: 'body of the Issue'
  assignees:
    description: 'Issue assignees'

# Define your outputs here.
outputs:
  time:
    description: 'The Time of Greeting'
  issue:
    description: 'The Issue object as a json string'

runs:
  using: node20
  main: dist/index.js
branding:
  icon: 'sunrise'
  color: 'orange'
