name: release and tag
on:
  release:
    types: [published, edited]
permissions:
  contents: read
  issues: write
  actions: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{github.event.release.tag_name}}
      - name: install deps
        run: npm ci
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
